#include <string>


using std::string;

string poem = "Hello world!\n";

poem += "another time...\n"

"yes, you are right\n"
"spectacular touhou world\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"In the name of the wise, to fool on behalf of the defense.\n"
"Hee hee, are all benefits to; world Rangrang, are all benefits to the.\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Reform does not stop, do not stop open.\n"
"Is an outstanding talent hidden\n"
"I do not admire is no way to chat with people using the power of others do?\n"
"Each one more book on a formula that would reduce by half the readers.\n"
"Sea Life, Too Late is not called courage, it takes courage to live.\n"
"Love is not exposed person is known to be alone in this dark Acacia.\n"
"I like you because I love you more than anyone on Earth, like you ...\n"
"Fight this thing, not just to guard what is it?\n"
"Never make mistakes ultimately nothing\n"
"Last thing we can not forget, but it must be put down.\n"
"What does not kill me, so that I will eventually become more powerful.\n"
"Everything is coming to an end all dream, break off. Something of the past also worry butterfly.\n"
"Paradise clean light, dark all day of break Hui, wind, fire disaster volts can, according puming world.\n"
"If the world does not like you, that it is my enemy.\n"
"The road is long Come, happiness and earth.\n"
"Snow firefly window to the case, for June glory.\n"
"Do not sun tan my skin, tanning my Mom and Dad's hair.\n"
"Fight this thing, not just to guard what is it?\n"
"Wang to admit, to allow the king, the king to bear this world!\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Does bear Kimi little bit reader Sashi昙Ri Not even rain of 鸣神\n"
"A willing heart, nothing is accomplished.\n"
"Midnight Rain Indus leaves, leaf sound is parting.\n"
"Some things we can not control, so control yourself.\n"
"Rhodes white teeth inside!\n"
"End of death, there is no God\n"
"Last year, this door today, Moment of truth.\n"
"Not like, not love. But more profound and heavy -\n"
"Home shouted from far, is to use non-autumn.\n"
"Mountains, white grass leaves yellow.\n"
"Yiling ancestors, five text a ten text three!\n"
"In most normal thing in the show can be a person of great character coming!\n"
"Valentine's night away from resentment, from the evening went so far as Acacia.\n"
"Come out, Keke Emperor!\n"
"Regardless of wind and waves, is worth a stroll.\n"
"Fish and can not have both, with the exception of the poor and single can\n"
"In addition to the age of firecrackers, vase into the Su Tu.\n"
"End of this life, there are only two ways: either dream of life, or the implementation of life.\n"
"I was too young to even know how to love her.\n"
"I do not know people who do not suffer, suffer no confidant.\n"
"Dream has always been easy to wake up.\n"
"Not been bad old stone, not cold water has frozen, the dead body is not there, not of the soul has been burning.\n"
"If you are in full bloom, the breeze unsolicited.\n"
"Do not sun tan my skin, tanning my Mom and Dad's hair.\n"
"Even days without rain, I would stay here.\n"
"Unhappy life all likelihood!\n"
"Cloud home. Ancient jade. Readily poetry. Nineteen of you.\n"
"The development of history is not the people's will transfer.\n"
"Our passing was to acquaintance or forgotten.\n"
"The goal is to force science above the super powers, in order to Timberland Hill glory.\n"
"Water clear, not because it does not contain impurities, but in understanding precipitate.\n"
"The strange thing is, when he died, all the people began to love him.\n"
"Desperate people do not home.\n"
"Pelting rain received residual heat, leaf shock Indus.\n"
"Difficult when you meet Bie Yinan, Dongfeng flowers residual weakness.\n"
"There are many others in this world home with misfortune, and gloating people.\n"
"Beautiful is not of this world, but your eyes see the world.\n"
"I Xiangmaotangtang Lee, wife of lilies and roses, how could you give birth to this mountain Mangfu it?\n"
"People born in faith, destroyed faith. People reborn in the ashes of faith.\n"
"Marco Polo For the West than the West, thick makeup.\n"
"This hand, temporarily do not wash\n"
"Will hesitate defeat, decisive will to white.\n"
"Frost blowing haired, white can be considered first.\n"
"Small sweet potatoes, I found you.\n"
"As long as you have, I will do anything.\n"
"Teenager listening to the rain song upstairs. Candle faint Luozhang.\n"
"The most famous than the one you want to die.\n"
"The strange thing is, when he died, all the people began to love him.\n"
"The development of history is not the people's will transfer.\n"
"Wang Meng won, lost Kyosuke\n"
"Good things, only now na.\n"
"To a career with no limits, has been useless! Yi Er is knower, the Scots just carry on!\n"
"Edge, fantastic\n"
"Ai such as the mountain snow, Jiao Ruoyun between months.\n"
"Wife is not life, it is a very strong insult, classy, ​​jade stones.\n"
"Looking for more useless than themselves, immersed in such a sense of superiority.\n"
"Huazipiaoling artesian water. Kind of Acacia, Xianchou.\n"
"Horse only, why their way?\n"
"Not solitary Ming Si-stricken, volume curtain Mochizuki empty sigh.\n"
"Life is a tragedy with a close-up view, it is a long shot to see comedy.\n"
"When friends do not need any qualifications.\n"
"We are an independent individual, not the lonely existence.\n"
"Regardless of wind and waves, is worth a stroll.\n"
"The development of history is not the people's will transfer.\n"
