#include <string>


using std::string;

string poem = "Hello world!\n";

poem += "another time...\n"

"yes, you are right\n"
"spectacular touhou world\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"In the name of the wise, to fool on behalf of the defense.\n"
"Hee hee, are all benefits to; world Rangrang, are all benefits to the.\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Reform does not stop, do not stop open.\n"
"Is an outstanding talent hidden\n"
"I do not admire is no way to chat with people using the power of others do?\n"
"Each one more book on a formula that would reduce by half the readers.\n"
"Sea Life, Too Late is not called courage, it takes courage to live.\n"
"Love is not exposed person is known to be alone in this dark Acacia.\n"
"I like you because I love you more than anyone on Earth, like you ...\n"
"Fight this thing, not just to guard what is it?\n"
"Never make mistakes ultimately nothing\n"
"Last thing we can not forget, but it must be put down.\n"
"What does not kill me, so that I will eventually become more powerful.\n"
"Everything is coming to an end all dream, break off. Something of the past also worry butterfly.\n"
"Paradise clean light, dark all day of break Hui, wind, fire disaster volts can, according puming world.\n"
"If the world does not like you, that it is my enemy.\n"
"The road is long Come, happiness and earth.\n"
"Snow firefly window to the case, for June glory.\n"
"Do not sun tan my skin, tanning my Mom and Dad's hair.\n"
"Fight this thing, not just to guard what is it?\n"
"Wang to admit, to allow the king, the king to bear this world!\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Does bear Kimi little bit reader Sashi昙Ri Not even rain of 鸣神\n"
"A willing heart, nothing is accomplished.\n"
"Midnight Rain Indus leaves, leaf sound is parting.\n"
"Some things we can not control, so control yourself.\n"
"Rhodes white teeth inside!\n"
"End of death, there is no God\n"
