#include <string>


using std::string;

string poem = "Hello world!\n";

poem += "another time...\n"

"yes, you are right\n"
"spectacular touhou world\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"test, and deploy your project.\n"
"In the name of the wise, to fool on behalf of the defense.\n"
"Hee hee, are all benefits to; world Rangrang, are all benefits to the.\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Reform does not stop, do not stop open.\n"
"Is an outstanding talent hidden\n"
"I do not admire is no way to chat with people using the power of others do?\n"
"Each one more book on a formula that would reduce by half the readers.\n"
"Sea Life, Too Late is not called courage, it takes courage to live.\n"
"Love is not exposed person is known to be alone in this dark Acacia.\n"
"I like you because I love you more than anyone on Earth, like you ...\n"
"Fight this thing, not just to guard what is it?\n"
"Never make mistakes ultimately nothing\n"
"Last thing we can not forget, but it must be put down.\n"
"What does not kill me, so that I will eventually become more powerful.\n"
"Everything is coming to an end all dream, break off. Something of the past also worry butterfly.\n"
"Paradise clean light, dark all day of break Hui, wind, fire disaster volts can, according puming world.\n"
"If the world does not like you, that it is my enemy.\n"
"The road is long Come, happiness and earth.\n"
"Snow firefly window to the case, for June glory.\n"
"Do not sun tan my skin, tanning my Mom and Dad's hair.\n"
"Fight this thing, not just to guard what is it?\n"
"Wang to admit, to allow the king, the king to bear this world!\n"
"Eros in person, torch-like, against the wind, there will be risk of burning the hands of\n"
"Does bear Kimi little bit reader Sashi昙Ri Not even rain of 鸣神\n"
"A willing heart, nothing is accomplished.\n"
"Midnight Rain Indus leaves, leaf sound is parting.\n"
"Some things we can not control, so control yourself.\n"
"Rhodes white teeth inside!\n"
"End of death, there is no God\n"
"Last year, this door today, Moment of truth.\n"
"Not like, not love. But more profound and heavy -\n"
"Home shouted from far, is to use non-autumn.\n"
"Mountains, white grass leaves yellow.\n"
"Yiling ancestors, five text a ten text three!\n"
"In most normal thing in the show can be a person of great character coming!\n"
"Valentine's night away from resentment, from the evening went so far as Acacia.\n"
"Come out, Keke Emperor!\n"
"Regardless of wind and waves, is worth a stroll.\n"
"Fish and can not have both, with the exception of the poor and single can\n"
"In addition to the age of firecrackers, vase into the Su Tu.\n"
"End of this life, there are only two ways: either dream of life, or the implementation of life.\n"
"I was too young to even know how to love her.\n"
"I do not know people who do not suffer, suffer no confidant.\n"
"Dream has always been easy to wake up.\n"
"Not been bad old stone, not cold water has frozen, the dead body is not there, not of the soul has been burning.\n"
"If you are in full bloom, the breeze unsolicited.\n"
"Do not sun tan my skin, tanning my Mom and Dad's hair.\n"
"Even days without rain, I would stay here.\n"
"Unhappy life all likelihood!\n"
"Cloud home. Ancient jade. Readily poetry. Nineteen of you.\n"
"The development of history is not the people's will transfer.\n"
"Our passing was to acquaintance or forgotten.\n"
"The goal is to force science above the super powers, in order to Timberland Hill glory.\n"
"Water clear, not because it does not contain impurities, but in understanding precipitate.\n"
"The strange thing is, when he died, all the people began to love him.\n"
"Desperate people do not home.\n"
"Pelting rain received residual heat, leaf shock Indus.\n"
"Difficult when you meet Bie Yinan, Dongfeng flowers residual weakness.\n"
"There are many others in this world home with misfortune, and gloating people.\n"
"Beautiful is not of this world, but your eyes see the world.\n"
"I Xiangmaotangtang Lee, wife of lilies and roses, how could you give birth to this mountain Mangfu it?\n"
"People born in faith, destroyed faith. People reborn in the ashes of faith.\n"
"Marco Polo For the West than the West, thick makeup.\n"
"This hand, temporarily do not wash\n"
"Will hesitate defeat, decisive will to white.\n"
"Frost blowing haired, white can be considered first.\n"
"Small sweet potatoes, I found you.\n"
"As long as you have, I will do anything.\n"
"Teenager listening to the rain song upstairs. Candle faint Luozhang.\n"
"The most famous than the one you want to die.\n"
"The strange thing is, when he died, all the people began to love him.\n"
"The development of history is not the people's will transfer.\n"
"Wang Meng won, lost Kyosuke\n"
"Good things, only now na.\n"
"To a career with no limits, has been useless! Yi Er is knower, the Scots just carry on!\n"
"Edge, fantastic\n"
"Ai such as the mountain snow, Jiao Ruoyun between months.\n"
"Wife is not life, it is a very strong insult, classy, ​​jade stones.\n"
"Looking for more useless than themselves, immersed in such a sense of superiority.\n"
"Huazipiaoling artesian water. Kind of Acacia, Xianchou.\n"
"Horse only, why their way?\n"
"Not solitary Ming Si-stricken, volume curtain Mochizuki empty sigh.\n"
"Life is a tragedy with a close-up view, it is a long shot to see comedy.\n"
"When friends do not need any qualifications.\n"
"We are an independent individual, not the lonely existence.\n"
"Regardless of wind and waves, is worth a stroll.\n"
"The development of history is not the people's will transfer.\n"
"I prefer to die of history. Dead history written with ink, the living history with blood.\n"
"In a non-hexyl, whether from human Valuation of gains and losses.\n"
"In terms of color to see me, and begged me to tone sound is pedestrian depraved, can not see the Tathagata.\n"
"When the tears stream down, know, separate is another to understand.\n"
"Perhaps the most excruciating not a tragic war, but tedious daily life.\n"
"Cloud Star break out of the night, I murmured star: swallow me.\n"
"Lonely people do not hurt others, we will only continue to hurt yourself Bale.\n"
"Wife is not life, it is a very strong insult, classy, ​​jade stones.\n"
"Lotus was exposed sharp angle, stand on top of already dragonfly.\n"
"Deceive the world and deceive you initially.\n"
"In terms of color to see me, and begged me to tone sound is pedestrian depraved, can not see the Tathagata.\n"
"Fortunately person's life are being cured childhood, unfortunate life in the cure childhood.\n"
"Some things I do not see through, not me stupid, but I'm too good.\n"
"Firecrackers Snooze, how can I miss you so wish\n"
"Remember that young, you love to sell Meng I love to laugh.\n"
"We are an independent individual, not the lonely existence.\n"
"Beautiful things exist in the world, which is in itself worthy of thanks.\n"
"Between the moonlight and snow color, you are stunning third\n"
"Thin world situation, human evil, rain sent to spend the evening easy to drop.\n"
"To day you go, I want you to stay\n"
"I do not know afterlife meet each other. Still be able to remember who I am?\n"
"People just have to lose, the play does not look good.\n"
"We are an independent individual, not the lonely existence.\n"
"I think your efforts will pay off certain\n"
"Will hesitate defeat, decisive will to white.\n"
"The Bowl, anything for autumn sad painted fans.\n"
"Paradise clean light, dark all day of break Hui, wind, fire disaster volts can, according puming world.\n"
"Regardless of wind and waves, is worth a stroll.\n"
"Mountain peak, there is the other side of the sea, long distance, eventually turning, bitter aftertaste, eventually sweet.\n"
"To a career with no limits, has been useless! Yi Er is knower, the Scots just carry on!\n"
"The best feeling, you know someone hesitantly.\n"
"If no Lihen teach fundus, do not believe the world is bald.\n"
"Zen else, I do not repair. You alone are my Zen, eye candy\n"
"I stood in the intersection, the gas can put those Hachu hexagonal snow melts.\n"
"Wait, not for you to come back, but to find an excuse not to leave.\n"
"Most people do not want to grow up, but no way to continue as a child\n"
"Cloud flower her capacity, spring whisk threshold Revlon.\n"
"Do not suffer from no place, suffering from it stand. Mo does not suffer from known, known also as required.\n"
"Choudao the flow of water, toast Xiaochou worry even more unhappy.\n"
"Perhaps the most excruciating not a tragic war, but tedious daily life.\n"
"As long as we breathe, there is hope.\n"
"stand up! Stand up ah! You are my legs now! Stand up ah!\n"
"Willing to southwest wind, into the eternal rest monarch pregnant.\n"
"Tomorrow compared to yesterday, today better suited to start.\n"
"Since then as now was not Juhuo, I would be the only light.\n"
"Honey, I put myself on your ear, you'll hear it.\n"
"I live in the Yangtze River head, You live the Yangtze River tail.\n"
"Only when people fear can be brave.\n"
"What is a rose? To grow beheaded head.\n"
"Yearned flowers, why not day and night.\n"
"I want to make you stronger, because at least I've had the opportunity to meet the people want to protect.\n"
"An exquisite dice red beans, Such is Life Acacia know I do not know.\n"
"Empty, lonely.\n"
"Which tube funeral before his death, the waves have a few days a few days.\n"
"We are an independent individual, not the lonely existence.\n"
"Everything can be passed, but it's impossible to go back to the past.\n"
"Tuvalu multi-hit!\n"
"There vegetation Conscience, who needs beauty discount!\n"
"Prime is not heavy, the day can no longer morning.\n"
"The day before yesterday a small rabbit, deer yesterday, today is you.\n"
