# This is a basic workflow to help you get started with Actions

name: machine-compose

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore: 
  #     - '**.md'
  schedule:
    - cron: '15 1 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Runs a single command using the runners shell
    - name: install dependency
      run: |
        sudo apt update
        sudo apt install -y curl git make

    # Runs a set of commands using the runners shell
    - name: auto commit and push
      env:
        GITKEY: ${{ secrets.GITKEY }}
      run: |          
        echo https://Wistral:${GITKEY}@github.com > ~/.git-credentials
        git config credential.helper store
        git config user.email "whistral@gmail.com"
        git config user.name "Wistral"
        python autocompose.py
        git push
        make
        ./read_poem
